// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUS0NTwCVw2cEC3d9hOqmJbieVfVQo4WY',
    appId: '1:901486566683:web:25c75680cc51ada6d0c7be',
    messagingSenderId: '901486566683',
    projectId: 'db-c4a09',
    authDomain: 'db-c4a09.firebaseapp.com',
    storageBucket: 'db-c4a09.appspot.com',
    measurementId: 'G-59HJQFPPG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ5HbbVu4dZkZT8zTFPC6TOHMGBH7RbIY',
    appId: '1:901486566683:android:704e7355d292f595d0c7be',
    messagingSenderId: '901486566683',
    projectId: 'db-c4a09',
    storageBucket: 'db-c4a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2czLIUvIWHpKpsCqf9uz4ApheYXbyK64',
    appId: '1:901486566683:ios:cebd232b0eede974d0c7be',
    messagingSenderId: '901486566683',
    projectId: 'db-c4a09',
    storageBucket: 'db-c4a09.appspot.com',
    iosBundleId: 'com.laporte.scatter3dCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2czLIUvIWHpKpsCqf9uz4ApheYXbyK64',
    appId: '1:901486566683:ios:cebd232b0eede974d0c7be',
    messagingSenderId: '901486566683',
    projectId: 'db-c4a09',
    storageBucket: 'db-c4a09.appspot.com',
    iosBundleId: 'com.laporte.scatter3dCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUS0NTwCVw2cEC3d9hOqmJbieVfVQo4WY',
    appId: '1:901486566683:web:92925b5d413e542cd0c7be',
    messagingSenderId: '901486566683',
    projectId: 'db-c4a09',
    authDomain: 'db-c4a09.firebaseapp.com',
    storageBucket: 'db-c4a09.appspot.com',
    measurementId: 'G-CF80P2Z48Q',
  );
}
